/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-28 02:25:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/inc/admin_header.jsp", Long.valueOf(1598578656568L));
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1598578656569L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Documents/GitHub/markethurryserver/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mhserver/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598578656497L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마켓허리 관리자 :: 상품관리</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mh/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mh/css/markethurry.css\">\r\n");
      out.write("<script src=\"/mh/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/mh/js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"/mh/js/Backstretch.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mh/css/admin_template.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mh/css/jquery-ui.css\" />\r\n");
      out.write("<script src=\"/mh/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/mh/js/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"/mh/js/highcharts.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<!-- 헤더 -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <img id=\"logoimg\" src=\"/mh/images/adminlogo.png\" alt=\"\"> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"home\"><div id=\"homeglyphicon\" class=\"glyphicon glyphicon-home\"></div>홈페이지 바로가기</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<div id=\"side\">\r\n");
      out.write("    <ul id=\"menu\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <!-- 상품 관리 메뉴(나중에 각 메뉴별로 href옵션에 링크 걸어야함) -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"glyphicon glyphicon-gift\"></div>\r\n");
      out.write("                <a id=\"item\">상품관리</a>\r\n");
      out.write("                <ul class=\"sublist\" id=\"itemlist\">\r\n");
      out.write("                    <li><a href=\"/mh/admin/product/searchproduct.do\">상품 조회</a></li>\r\n");
      out.write("                    <li><a href=\"/mh/admin/product/enrollproduct.do\">상품 등록</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 주문 관리 메뉴 -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"glyphicon glyphicon-shopping-cart\"></div>\r\n");
      out.write("                <a id=\"order\">주문관리</a>\r\n");
      out.write("                <ul class=\"sublist\" id=\"orderlist\">\r\n");
      out.write("                    <li><a href=\"/mh/admin/order/totalorder.do\">전체 주문 목록</a></li>\r\n");
      out.write("                    <li><a href=\"\">배송 관리</a></li>\r\n");
      out.write("                    <li><a href=\"/mh/admin/order/cancelorder.do\">취소 / 교환 / 환불</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 고객 관리 메뉴 -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"glyphicon glyphicon-user\"></div>\r\n");
      out.write("                <a href=\"/mh/admin/member/member.do\" id=\"customer\">고객관리</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 게시판 관리 메뉴 -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"glyphicon glyphicon-list-alt\"></div>\r\n");
      out.write("                <a id=\"border\">게시판관리</a>\r\n");
      out.write("                <ul class=\"sublist\" id=\"borderlist\">\r\n");
      out.write("                    <li><a href=\"/mh/admin/board/notice.do\">공지사항 관리</a></li>\r\n");
      out.write("                    <li><a href=\"/mh/admin/board/event.do\">이벤트 관리</a></li>\r\n");
      out.write("                    <li><a href=\"/mh/admin/board/ask.do\">상품문의 관리</a></li>\r\n");
      out.write("                    <li><a href=\"/mh/admin/board/review.do\">상품후기 관리</a></li>\r\n");
      out.write("                    <li><a href=\"/mh/admin/board/myrecipeboard.do\">나만의 레시피 관리</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 통계 관리 메뉴 -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"glyphicon glyphicon-signal\"></div>\r\n");
      out.write("                <a id=\"static\">통계관리</a>\r\n");
      out.write("                <ul class=\"sublist\" id=\"staticlist\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <a href=\"#\" id=\"sales\">매출분석</a>\r\n");
      out.write("                        <ul class=\"subsublist\" id=\"saleslist\">\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/salesdaily.do\">일별 매출</a></li>\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/salesweekly.do\">주별 매출</a></li>\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/salesmonthly.do\">월별 매출</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <a id=\"items\">상품분석</a>\r\n");
      out.write("                        <ul class=\"subsublist\" id=\"itemslist\">\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/productranking.do\">판매상품 순위</a></li>\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/categoryranking.do\">판매분류 순위</a></li>\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/cancel.do\">취소/반품 순위</a></li>\r\n");
      out.write("                            <li><a href=\"/mh/admin/statistics/shoopingcartstat.do\">장바구니 상품 분석</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t#menustep {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #menustep > span {\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            color: #999999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #menuname > span {\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #666666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("         /* 상단 헤더 */\r\n");
      out.write("         #headerTitle {\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 30px auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*  */\r\n");
      out.write("        #searchOrder {\r\n");
      out.write("            /* 검색 감싸기 */\r\n");
      out.write("            border:none;\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #searchOrder > div > div {\r\n");
      out.write("            background-color: #F3F3F3;\r\n");
      out.write("            border-right: 1px solid #ccc;\r\n");
      out.write("            width: 180px;\r\n");
      out.write("            height: 58px;\r\n");
      out.write("            padding-top: 18px;\r\n");
      out.write("            padding-left: 8px;\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #sel1 {\r\n");
      out.write("            /* 검색어의 주문번호*/\r\n");
      out.write("            border:1px solid #ccc;\r\n");
      out.write("            margin: 16px 10px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #txt1,\r\n");
      out.write("        #txt2  {\r\n");
      out.write("            /* 검색어 & 상품 text box */\r\n");
      out.write("            border:1px solid #ccc;\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        #date1 {\r\n");
      out.write("            /* 기간 */\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            margin-top: 11px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #taste {\r\n");
      out.write("            /* 기간 물결 */\r\n");
      out.write("            margin: auto 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #sel2 {\r\n");
      out.write("            /* 상품 감싸기 */\r\n");
      out.write("            margin: 16px 8px;\r\n");
      out.write("            width: 85px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .btnSearch { \r\n");
      out.write("            outline: none;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            padding-top: 10px;\r\n");
      out.write("            padding-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        #btn1 {\r\n");
      out.write("            /* 검색 버튼 */\r\n");
      out.write("            background-color: #ccc;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #orderBtn {\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            \r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #SearchWord,\r\n");
      out.write("        /* #period, */\r\n");
      out.write("        #product,\r\n");
      out.write("        #price {\r\n");
      out.write("            /* 검색어,기간,상품 상자*/\r\n");
      out.write("            border: 1px solid #ccc;  \r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #period {\r\n");
      out.write("            border: 1px solid #ccc;  \r\n");
      out.write("            /* border-bottom: none; */\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product {\r\n");
      out.write("            /* 상품 상자*/\r\n");
      out.write("            border: 1px solid #ccc;;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchresult {\r\n");
      out.write("            /* 검색결과 안 박스 감싸기 */\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchresult {\r\n");
      out.write("            margin: 70px 40px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #666666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .SearchResultBox {\r\n");
      out.write("            /* 검색결과 안 박스 메뉴들 */\r\n");
      out.write("            width: 310px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #result {\r\n");
      out.write("            border: none;\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #orderResult {\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        #deleteBtn {\r\n");
      out.write("            background-color: #ccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #secondBtn {\r\n");
      out.write("            width: 1570px;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("    <!-- 전체 내용을 묶는 div#container -->\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 상단 카테고리를 묶는 div#headerTitle -->\r\n");
      out.write("    <div id=\"headerTitle\">\r\n");
      out.write("        <div id=\"menustep\"><span>홈 > 상품관리 > 상품조회</span></div>\r\n");
      out.write("        <div id=\"menuname\"><span>상품조회</span></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        <!-- 종류별 검색을 진행하는 div#searchOrder -->\r\n");
      out.write("        <div id=\"searchOrder\">\r\n");
      out.write("            <div id=\"SearchWord\">\r\n");
      out.write("                <div>검색 분류</div>\r\n");
      out.write("                <select id=\"sel1\">\r\n");
      out.write("                    <option>분류 선택</option>\r\n");
      out.write("                    <option>상품명</option>\r\n");
      out.write("                    <option>상품번호</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"text\" id=\"txt1\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"product\">\r\n");
      out.write("                <div>상품 분류</div>\r\n");
      out.write("                <select id=\"sel2\">\r\n");
      out.write("                    <option>분류 선택</option>\r\n");
      out.write("                    <option>채소</option>\r\n");
      out.write("                    <option>과일</option>\r\n");
      out.write("                    <option>육류</option>\r\n");
      out.write("                    <option>수산</option>\r\n");
      out.write("                    <option>가공식품</option>\r\n");
      out.write("                    <option>소스</option>\r\n");
      out.write("                    <option>유제품</option>\r\n");
      out.write("                    <option>건강식품</option>\r\n");
      out.write("                    <option>음료</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"text\" id=\"txt2\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"price\">\r\n");
      out.write("                <div>상품 금액</div>\r\n");
      out.write("                <input type=\"text\" id=\"startPrice\" style=\"margin-left: 10px; margin-top: 11px; text-align: right;\"><span>원</span>\r\n");
      out.write("                <span style=\"margin: auto 20px;\"> ~ </span>\r\n");
      out.write("                <input type=\"text\" id=\"endPrice\" style=\"text-align: right;\"><span> 원</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"period\">\r\n");
      out.write("                <div>등록일</div>\r\n");
      out.write("                <input type=\"text\" id=\"date1\" style=\"margin-left: 10px; margin-top: 11px;\" disabled>\r\n");
      out.write("                <span style=\"margin: auto 20px;\">~</span>\r\n");
      out.write("                <input type=\"text\" id=\"date2\" disabled>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 검색 버튼을 묶는 orderBtn-->\r\n");
      out.write("        <div id=\"orderBtn\">\r\n");
      out.write("            <button type=\"submit\" id=\"btn1\" class=\"btnSearch\">검색</button>\r\n");
      out.write("            <input type=\"button\" value=\"초기화\" id=\"btn2\" class=\"btnSearch\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 검색 결과 헤더를 묶는 div#ResultHeader -->\r\n");
      out.write("        <div id=\"searchresult\">▶ 검색결과</div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"result\">\r\n");
      out.write("            <div id=\"orderResult\">검색결과 ( <span id=\"resultCount\" style=\"color: red;\">0</span>건 )</div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- 검색 결과 내용을 묶는 div#result -->\r\n");
      out.write("        <!-- <div style=\"width: 1570px; margin: 20px 55px;\"> -->\r\n");
      out.write("            <table id=\"resultTable\" class=\"table table-bordered\">\r\n");
      out.write("                <tr style=\"text-align:center;\">\r\n");
      out.write("                    <th>\r\n");
      out.write("                        <input type=\"checkbox\" id=\"allCheck\">\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <th>상품번호</th>\r\n");
      out.write("                    <th>상품 분류</th>\r\n");
      out.write("                    <th>상품명</th>\r\n");
      out.write("                    <th>상품 금액</th>\r\n");
      out.write("                    <th>상품 등록일</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("                \r\n");
      out.write("                <!-- <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"checkbox\" id=\"c1\" class=\"productCheck\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>125</td>\r\n");
      out.write("                    <td>채소</td>\r\n");
      out.write("                    <td>애호박 1개</td>\r\n");
      out.write("                    <td class=\"tblPrice\"><span>1,480</span><span>원</span></td>\r\n");
      out.write("                    <td>2020-07-11</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"checkbox\" id=\"c2\" class=\"productCheck\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>312</td>\r\n");
      out.write("                    <td>과일</td>\r\n");
      out.write("                    <td>자두(1kg)</td>\r\n");
      out.write("                    <td class=\"tblPrice\"><span>8,900</span><span>원</span></td>\r\n");
      out.write("                    <td>2020-07-13</td>\r\n");
      out.write("                </tr> -->\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 수정, 삭제 버튼을 묶는 div#modDelBtn -->\r\n");
      out.write("         <!-- 삭제 버튼 -->\r\n");
      out.write("         <div id=\"secondBtn\"><input type=\"button\" value=\"삭제\" id=\"deleteBtn\" class=\"btnSearch\" /></div>\r\n");
      out.write("\r\n");
      out.write("    <!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        // 전체 체크 순회\r\n");
      out.write("        // $(\"input:checkbox[name=is_check]\").each(function() {\r\n");
      out.write("        //     this.checked = true;\r\n");
      out.write("        // });\r\n");
      out.write("\r\n");
      out.write("        // 체크박스 전체선택\r\n");
      out.write("        var check = true;\r\n");
      out.write("\r\n");
      out.write("        $(\"#allCheck\").click(function() {\r\n");
      out.write("            if (check) {\r\n");
      out.write("                // $(\"#c1\").prop(\"checked\", true);\r\n");
      out.write("                // $(\"#c2\").prop(\"checked\", check)\r\n");
      out.write("                $(\"input:checkbox[class=productCheck]\").each(function() {\r\n");
      out.write("                    this.checked = check;\r\n");
      out.write("                });\r\n");
      out.write("                check = false;\r\n");
      out.write("            } else {\r\n");
      out.write("                // $(\"#c1\").prop(\"checked\", check);\r\n");
      out.write("                // $(\"#c2\").prop(\"checked\", check);\r\n");
      out.write("                $(\"input:checkbox[class=productCheck]\").each(function() {\r\n");
      out.write("                    this.checked = check;\r\n");
      out.write("                });\r\n");
      out.write("                check = true;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        // datepicker 출력\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $(\"#date1\").datepicker({\r\n");
      out.write("                dateFormat: \"yy-mm-dd\",\r\n");
      out.write("                showOn: \"both\",\r\n");
      out.write("                buttonImage: \"/mh/images/icons8-calendar-28.png\",\r\n");
      out.write("                buttonImageOnly: true,\r\n");
      out.write("                buttonText: \"Select date\"\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(\"#date2\").datepicker({\r\n");
      out.write("                dateFormat: \"yy-mm-dd\",\r\n");
      out.write("                showOn: \"both\",\r\n");
      out.write("                buttonImage: \"/mh/images/icons8-calendar-28.png\",\r\n");
      out.write("                buttonImageOnly: true,\r\n");
      out.write("                buttonText: \"Select date\"\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 검색버튼 클릭\r\n");
      out.write("        $(\"#btn1\").click(function() {\r\n");
      out.write("\r\n");
      out.write("            // 항목이 모두 빈칸이면 전체검색\r\n");
      out.write("            if ( ($(\"#txt1\").val() == \"\") && ($(\"#txt2\").val() == \"\") \r\n");
      out.write("                && ($(\"#startPrice\").val() == \"\") && ($(\"#endPrice\").val() == \"\")\r\n");
      out.write("                && ($(\"#date1\").val() == \"\") && ($(\"#date2\").val() == \"\") ) {\r\n");
      out.write("                    alert(\"전체 검색\");\r\n");
      out.write("                } \r\n");
      out.write("                \r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 초기화버튼 클릭\r\n");
      out.write("        $(\"#btn2\").click(function() {\r\n");
      out.write("            $(\"#txt1\").val(\"\");\r\n");
      out.write("            $(\"#txt2\").val(\"\");\r\n");
      out.write("            $(\"#startPrice\").val(\"\");\r\n");
      out.write("            $(\"#endPrice\").val(\"\");\r\n");
      out.write("            $(\"#date1\").val(\"\");\r\n");
      out.write("            $(\"#date2\").val(\"\");\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        // 천단위 , 찍기\r\n");
      out.write("        function numberWithCommas(x) {\r\n");
      out.write("            return x.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var productprice = $(\"#productprice\").text();\r\n");
      out.write("        \r\n");
      out.write("        $(\".productprice\").each(function(index, item){\r\n");
      out.write("        \tvar beforeprice = $(item).text();\r\n");
      out.write("        \t$(item).text(numberWithCommas(beforeprice));\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        // var startPrice;\r\n");
      out.write("        // 가격 칸 천단위 찍어주기\r\n");
      out.write("        // $(\"#startPrice\").on(\"input\", function() {\r\n");
      out.write("        // });\r\n");
      out.write("        //     startPrice = $(\"#startPrice\").val();\r\n");
      out.write("        // $(\"#startPrice\").val(numberWithCommas(startPrice));\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        // 테이블의 행 갯수 (지금은 검색된 결과의 갯수)\r\n");
      out.write("        // 1을 뺀 이유는 헤더부분(첫 행) 제외\r\n");
      out.write("        var resultCount = $(\"#resultTable tbody tr\").length - 1;\r\n");
      out.write("\r\n");
      out.write("        // 검색결과 몇건인지\r\n");
      out.write("        $(\"#resultCount\").text(resultCount);\r\n");
      out.write("\r\n");
      out.write("        // 수정버튼 클릭\r\n");
      out.write("        $(\"#modifyBtn\").click(function() {\r\n");
      out.write("           // 체크된 갯수\r\n");
      out.write("            var checkCount = $(\"input:checkbox[class=productCheck]:checked\").length;\r\n");
      out.write("            // console.log(checkCount);\r\n");
      out.write("            if (checkCount == 0) alert(\"수정하려는 상품을 선택하세요.\");\r\n");
      out.write("            else {\r\n");
      out.write("                // 수정 폼으로 이동\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 삭제버튼 클릭\r\n");
      out.write("        $(\"#deleteBtn\").click(function() {\r\n");
      out.write("            // 체크된 갯수\r\n");
      out.write("            var checkCount = $(\"input:checkbox[class=productCheck]:checked\").length;\r\n");
      out.write("            // console.log(checkCount);\r\n");
      out.write("            if (checkCount == 0) alert(\"삭제하려는 상품을 선택하세요.\");\r\n");
      out.write("            else {\r\n");
      out.write("                $(\"input:checkbox[class=productCheck]:checked\").parent().parent().remove();\r\n");
      out.write("                alert(\"삭제가 완료되었습니다.\");\r\n");
      out.write("                resultCount = resultCount - checkCount;\r\n");
      out.write("                $(\"#resultCount\").text(resultCount);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $(\"#txt1\").focus(function() {\r\n");
      out.write("        \t$(this).attr(\"value\", \"\");\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        $(\"#txt1\").keyup(function() {\r\n");
      out.write("\r\n");
      out.write("        if(event.keyCode ==  13){\r\n");
      out.write("        \tvar search = $(\"#txt1\").val();\r\n");
      out.write("        \tlocation.href=\"/mh/admin/product/searchproduct.do?search=\"+search;\r\n");
      out.write("        }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $(\"#btn1\").click(function(){\r\n");
      out.write("        \tvar search = $(\"#txt1\").val();\r\n");
      out.write("        \tlocation.href=\"/mh/admin/product/searchproduct.do?search=\" +search;\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"/mh/js/admin_template.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/product/searchproduct.jsp(283,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/product/searchproduct.jsp(283,16) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/admin/product/searchproduct.jsp(283,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                \r\n");
            out.write("                <tr>\r\n");
            out.write("                \t<td><input type=\"checkbox\" class=\"productCheck\"></td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                    <td class=\"productprice\" style=\"text-align: right;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("                \r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/product/searchproduct.jsp(297,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty search and list.size() == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t           \t<tr style=\"text-align:center;\">\r\n");
          out.write("\t           \t\t<td colspan=\"6\">검색 결과가 없습니다.</td>\r\n");
          out.write("\t           \t</tr>                    \t\r\n");
          out.write("\t\t        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
